---

players:
  SteamNick1: 13123discordIDhere123123
  SteamNick2: 23123discordIDhere123123

webhooks:
  RegularGaem: https://discordapp.com/webhook0
  SupaAwesomeGaem: https://discordapp.com/webhook1

debugWebhook: https://when-all-goes-bonkers